### ISSUE TITLE
Cannot start container keep getting even error. How to solve this?

### ISSUE THREAD

**Issue by BobWs** [arugifa/standardnotes-server-docker#2]
Hi,
I have installed your image on docker but I keep getting this error message and the container will not start. Any idea how to solve this?

`/bin/sh: bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0: not found
`

**Comment by zakiur** [comment]
Try `use "bundle exec rake secret"` for `SECRET_KEY_BASE` env.
Also on docker for anyone interested passing `DB_PORT` for env allows for custom port.
And for `DB_HOST` it will be the network gateway given Mariadb is in same network.
These are just my settings running in docker, using portainer, might not work for you.

**Comment by BobWs** [comment]
> use "bundle exec rake secret"

not working for me keep getting the same error and the container wouldn't start.
Any other tips?

**Comment by BobWs** [comment]
Found it this did the trick for me:
`sh -c while ! nc -vz standardnotes-db 3306 ; do sleep 10 ; done &&bundle exec rails db:migrate &&bundle exec rails server -b 0.0.0.0`
Needed to change `msql` into mine mariadb host `standardnotes-db`
