### ISSUE TITLE
Keep seeing these warning messages in the log

### ISSUE THREAD

**Issue by BobWs** [arugifa/standardnotes-server-docker#4]
``/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/stack.rb:35: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
stdout
04:09:57
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:109: warning: The called method `initialize' is defined here
stdout`
04:09:59`
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_adapters/`abstract_mysql_adapter.rb:167: warning: Using the last argument as keyword parameters is `deprecated; maybe ** should be added to the call
stdout`
04:09:59`
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_adapters/column.rb:16: warning: The called method `initialize' is defined here`
stdout`
04:09:59`
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/transactions.rb:210: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call`
stdout`
04:09:59`
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:228: warning: The called method `transaction' is defined here`
stdout`
04:09:59`
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:126: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call`
stdout`
04:09:59`
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:47: warning: The called method `initialize' is defined here`
stdout`
04:09:59`
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/persistence.rb:554: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call`
stdout`
04:09:59`
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/timestamp.rb:105: warning: The called method `_update_record' is defined here`
stdout`
04:09:59`
/usr/local/bundle/gems/activemodel-5.1.7/lib/active_model/type/integer.rb:11: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call`
stdout`
04:09:59`
/usr/local/bundle/gems/activemodel-5.1.7/lib/active_model/type/value.rb:6: warning: The called method `initialize' is defined here`
stdout`
04:10:06`
``

Keep seeing these warning messages in the log. What do they mean? How to solve it? Or Can I ignore them?

**Comment by arugifa** [comment]
Hi @BobWs ,

Thanks for your feedback.

I believe these logs come from an internal Ruby library. If the server works fine (i.e., the UI doesn't crash), then there is nothing to worry about :)

From what I can see, one of the libraries is calling some function in a deprecated way. The library's author should fix that in order for the message to disappear.

**Comment by arugifa** [comment]
As the author of Standard Notes published some time ago an image of the server, I would highly recommend using it instead of mine though :) 

https://hub.docker.com/r/standardnotes/syncing-server

**Comment by BobWs** [comment]
Hi,
Thanks for replying.
I switched to the official image and everything is fine now.

**Comment by arugifa** [comment]
Amazing! Thanks for your feedback :+1:
